source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZQCustomPicker_Example', :exclusive => true do
  pod "ZQCustomPicker", :path => "../"
end

target 'ZQCustomPicker_Tests', :exclusive => true do
  pod "ZQCustomPicker", :path => "../"

  
end
